const cards = [
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: '../src/assets/img/cry.jpg',
      audioSrc: '../src/assets/audio/cry.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: '../src/assets/img/dance.jpg',
      audioSrc: '../src/assets/audio/dance.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: '../src/assets/img/dive.jpg',
      audioSrc: '../src/assets/audio/dive.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: '../src/assets/img/draw.jpg',
      audioSrc: '../src/assets/audio/draw.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: '../src/assets/img/fish.jpg',
      audioSrc: '../src/assets/audio/fish.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: '../src/assets/img/fly.jpg',
      audioSrc: '../src/assets/audio/fly.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: '../src/assets/img/hug.jpg',
      audioSrc: '../src/assets/audio/hug.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: '../src/assets/img/jump.jpg',
      audioSrc: '../src/assets/audio/jump.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: '../src/assets/img/open.jpg',
      audioSrc: '../src/assets/audio/open.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'play',
      translation: 'играть',
      image: '../src/assets/img/play.jpg',
      audioSrc: '../src/assets/audio/play.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: '../src/assets/img/point.jpg',
      audioSrc: '../src/assets/audio/point.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: '../src/assets/img/ride.jpg',
      audioSrc: '../src/assets/audio/ride.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: '../src/assets/img/run.jpg',
      audioSrc: '../src/assets/audio/run.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: '../src/assets/img/sing.jpg',
      audioSrc: '../src/assets/audio/sing.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: '../src/assets/img/skip.jpg',
      audioSrc: '../src/assets/audio/skip.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: '../src/assets/img/swim.jpg',
      audioSrc: '../src/assets/audio/swim.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'armchair',
      translation: 'кресло',
      image: '../src/assets/img/armchair.jpg',
      audioSrc: '../src/assets/audio/armchair.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'bed',
      translation: 'кровать',
      image: '../src/assets/img/bed.jpg',
      audioSrc: '../src/assets/audio/bed.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'chair',
      translation: 'стул',
      image: '../src/assets/img/chair.jpg',
      audioSrc: '../src/assets/audio/chair.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'lamp',
      translation: 'лампа',
      image: '../src/assets/img/lamp.jpg',
      audioSrc: '../src/assets/audio/lamp.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'mirror',
      translation: 'зеркало',
      image: '../src/assets/img/mirror.jpg',
      audioSrc: '../src/assets/audio/mirror.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'picture',
      translation: 'картина',
      image: '../src/assets/img/picture.jpg',
      audioSrc: '../src/assets/audio/picture.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'sofa',
      translation: 'диван',
      image: '../src/assets/img/coach.jpg',
      audioSrc: '../src/assets/audio/sofa.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'table',
      translation: 'стол',
      image: '../src/assets/img/table.jpg',
      audioSrc: '../src/assets/audio/table.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'vase',
      translation: 'ваза',
      image: '../src/assets/img/vase.jpg',
      audioSrc: '../src/assets/audio/vase.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'wardrobe',
      translation: 'гардеробный шкаф',
      image: '../src/assets/img/wardrobe.jpg',
      audioSrc: '../src/assets/audio/wardrobe.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: '../src/assets/img/cat.jpg',
      audioSrc: '../src/assets/audio/cat.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: '../src/assets/img/chick.jpg',
      audioSrc: '../src/assets/audio/chick.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: '../src/assets/img/chicken.jpg',
      audioSrc: '../src/assets/audio/chicken.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: '../src/assets/img/dog.jpg',
      audioSrc: '../src/assets/audio/dog.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: '../src/assets/img/horse.jpg',
      audioSrc: '../src/assets/audio/horse.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: '../src/assets/img/pig.jpg',
      audioSrc: '../src/assets/audio/pig.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: '../src/assets/img/rabbit.jpg',
      audioSrc: '../src/assets/audio/rabbit.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: '../src/assets/img/sheep.jpg',
      audioSrc: '../src/assets/audio/sheep.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: '../src/assets/img/bird.jpg',
      audioSrc: '../src/assets/audio/bird.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: '../src/assets/img/fish1.jpg',
      audioSrc: '../src/assets/audio/fish.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: '../src/assets/img/frog.jpg',
      audioSrc: '../src/assets/audio/frog.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: '../src/assets/img/giraffe.jpg',
      audioSrc: '../src/assets/audio/giraffe.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: '../src/assets/img/lion.jpg',
      audioSrc: '../src/assets/audio/lion.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: '../src/assets/img/mouse.jpg',
      audioSrc: '../src/assets/audio/mouse.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: '../src/assets/img/turtle.jpg',
      audioSrc: '../src/assets/audio/turtle.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: '../src/assets/img/dolphin.jpg',
      audioSrc: '../src/assets/audio/dolphin.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'doctor',
      translation: 'докторишка',
      image: '../src/assets/img/doctor.jpg',
      audioSrc: '../src/assets/audio/doctor.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'teacher',
      translation: 'учитель',
      image: '../src/assets/img/teacher.jpg',
      audioSrc: '../src/assets/audio/teacher.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'artist',
      translation: 'артистишка (художник)',
      image: '../src/assets/img/artist.jpg',
      audioSrc: '../src/assets/audio/artist.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'businessman',
      translation: 'бизнесменчик',
      image: '../src/assets/img/businessman.jpg',
      audioSrc: '../src/assets/audio/businessman.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'farmer',
      translation: 'фермеришка',
      image: '../src/assets/img/farmer.jpg',
      audioSrc: '../src/assets/audio/farmer.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'journalist',
      translation: 'журналюга',
      image: '../src/assets/img/journalist.jpg',
      audioSrc: '../src/assets/audio/journalist.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'musician',
      translation: 'музыкантишка',
      image: '../src/assets/img/musician.jpg',
      audioSrc: '../src/assets/audio/musician.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'sailor',
      translation: 'морячок',
      image: '../src/assets/img/sailor.jpg',
      audioSrc: '../src/assets/audio/sailor.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: '../src/assets/img/skirt.jpg',
      audioSrc: '../src/assets/audio/skirt.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: '../src/assets/img/pants.jpg',
      audioSrc: '../src/assets/audio/pants.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: '../src/assets/img/blouse.jpg',
      audioSrc: '../src/assets/audio/blouse.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: '../src/assets/img/dress.jpg',
      audioSrc: '../src/assets/audio/dress.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: '../src/assets/img/boot.jpg',
      audioSrc: '../src/assets/audio/boot.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: '../src/assets/img/shirt.jpg',
      audioSrc: '../src/assets/audio/shirt.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: '../src/assets/img/coat.jpg',
      audioSrc: '../src/assets/audio/coat.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: '../src/assets/img/shoe.jpg',
      audioSrc: '../src/assets/audio/shoe.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: '../src/assets/img/sad.jpg',
      audioSrc: '../src/assets/audio/sad.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: '../src/assets/img/angry.jpg',
      audioSrc: '../src/assets/audio/angry.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: '../src/assets/img/happy.jpg',
      audioSrc: '../src/assets/audio/happy.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: '../src/assets/img/tired.jpg',
      audioSrc: '../src/assets/audio/tired.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: '../src/assets/img/surprised.jpg',
      audioSrc: '../src/assets/audio/surprised.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: '../src/assets/img/scared.jpg',
      audioSrc: '../src/assets/audio/scared.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: '../src/assets/img/smile.jpg',
      audioSrc: '../src/assets/audio/smile.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: '../src/assets/img/laugh.jpg',
      audioSrc: '../src/assets/audio/laugh.mp3',
      clicks: '0',
      rightClick: '0',
      wrongClick: '0',
      percent: '0',
    },
  ],
];

export default cards;
